// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

import jakarta.persistence.*;
import lombok.*;

@Setter
@Getter
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "\"residente\"")
public class Residente
 {

  @Column(name = "tempo")
  public String tempo;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  public Integer id;

}
