// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

import jakarta.persistence.*;
import lombok.*;

@Setter
@Getter
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "\"residente\"")
public class Residente {

  @Column(name = "tipoAbb")
  public String tipo;

  @Column(name = "tempo")
  public String tempo;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  public Integer id;

  public String getTipo() {
    return tipo;
  }

  public String getTempo() {
    return tempo;
  }

  public Integer getId() {
    return id;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public void setTempo(String tempo) {
    this.tempo = tempo;
  }
}
