// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

public class Sensore extends Sistema
 {

  public String id;

  public void rilevaVeicolo(){}

  public void leggiTarga(){}
}
