// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

import jakarta.persistence.*;
import lombok.*;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "\"sensore\"")
public class Sensore
 {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  public Integer id;

  @Column(name = "nome")
  public String nome;

  public String getNome() {
   return nome;
  }

  public Integer getId() {
   return id;
  }

  public void setId(Integer id) {
   this.id = id;
  }

  public void setNome(String nome) {
   this.nome = nome;
  }

  public void rilevaVeicolo(){}

  public void leggiTarga(){}
}
