// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

import jakarta.persistence.*;
import lombok.*;

@Setter
@Getter
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "\"sistema\"")
public class Sistema {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "cod")
    public String cod;

    public void registraUtente(){}

    public void generaQR(){}

    public void verificaAccesso(){}

    public void notificaConducente(){}

    public void generaMulta(){}

    public void verificaStatoRegolarita(){}

    public void addebitaTariffaAggiuntiva(){}
}
