// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

public class Sistema {

    public String cod;

    public void registraUtente(){}

    public void generaQR(){}

    public void verificaAccesso(){}

    public void notificaConducente(){}

    public void generaMulta(){}

    public void verificaStatoRegolarita(){}

    public void addebitaTariffaAggiuntiva(){}
}
