// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

import jakarta.persistence.*;
import lombok.*;

@Setter
@Getter
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "\"visitatore\"")
public class VisitatoreOccasionale {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Integer id;

    @Column(name = "tempo")
    public Integer tempo;

    public void pagaTariffaAggiuntiva(){}

    public void estendiTempo(){}

    public void dichiaraTempoPermanenza(){}

    public void validaUscita(){}

    public void closeSession(){}

    public void pagaTariffaOraria(){}

}
