// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.example.demo.src_gen.diagrammi_uml;

public class VisitatoreOccasionale extends Utente {

    public Abbonamento abbonamento;
    public String tempo;

    public void pagaTariffaAggiuntiva(){}

    public void estendiTempo(){}

    public void dichiaraTempoPermanenza(){}

    public void validaUscita(){}

    public void closeSession(){}

    public void pagaTariffaOraria(){}

}
